### ISSUE TITLE
cursor disapper at the input position.

### ISSUE THREAD

**Issue by iysheng** [Luxed/ayu-vim#15]
I found the cursor can be `disapper`, and i could not distinguish the cursor color.just as:
![](https://s3.bmp.ovh/imgs/2021/08/f4aab3fd103b0077.png)
Is the colorscheme set or my vimrc config is not so correct?

**Comment by Luxed** [comment]
This depends on your terminal. I have answered a similar issue in ayu-theme/ayu-vim#65.
What terminal are you using? Have you tried changing your terminal's cursor color?

**Comment by iysheng** [comment]
Thanks, I use `alacrity` as the terminal. I use dracula colorscheme on this terminal, after i use the default color, the cursor can be seen.
