### ISSUE TITLE
Request: Support neovim diagnostic highlight groups

### ISSUE THREAD

**Issue by bmulholland** [Luxed/ayu-vim#17]
Reference: https://github.com/sainnhe/sonokai/commit/9f7deaebdf92e02b447f59420331f42882e4e639

Details: https://github.com/neovim/neovim/pull/15585

**Comment by Luxed** [comment]
I have added support for these new groups! It seems to be working but I haven't tested it a whole lot. Feel free to reopen if you think something is missing or not working as expected!
