### ISSUE TITLE
Getting W18 warnings on vim startup

### ISSUE THREAD

**Issue by fifididi** [Luxed/ayu-vim#20]
Vim version: 9.0

I am getting `W18: Invalid character in group name` errors on line 15, 311, 312, 313 and 316 of `colors/ayu.vim`

**Comment by Luxed** [comment]
Interesting, I thought those would be on the lines I recently changed for the latest neovim updates.
I'll check that and close this ticket once it's fixed

**Comment by Luxed** [comment]
Fixed by commit https://github.com/Luxed/ayu-vim/commit/34e09f617f7986d871908d0dacb244f4b3f04aab
It seems like Vim doesn't like the `@highlight` syntax that Neovim uses.
