### ISSUE TITLE
Override default hex colors?

### ISSUE THREAD

**Issue by WirlyWirly** [Luxed/ayu-vim#23]
Hello,

I've been using the original ayu repo for quite sometime, I only just now found this fork and am making the switch.

I'm wanting to change a few of the hex colors, such as the `editor_bg` and `editor_findMatch_inactive` in the `autoload/ayu.vim` file. They're very similar and impossible for me to differentiate.

I can make these changes by over-riding them in-file, however I'm wondering if there's a way to do it without losing those changes when I update.

My knowledge on theming is almost non-existent, it took me a minute to even find this file.

Any tips?

**Comment by Luxed** [comment]
Each and every theme does things differently, so it's difficult to understand at first, but it really isn't all that complicated.
What you will need is `:h hi` (the highlight command).
Then, you can setup yourself up with [this simple snippet to customize the theme to your liking](https://github.com/Luxed/ayu-vim#customize-the-theme-to-your-liking).
Once that's done, you have two options:

1. Follow what written in the example and use the highlight function provided by the theme (to make use of the included color palette that you found in `autoload/ayu.vim`).
    With this solution, my suggestion would be to add something like `call ayu#hi('Search', 'editor_findMatch_active', '')` to make the `Search` highlight group more vibrant.
    (Keep in mind that you can find what highlight groups are defined in `colors/ayu.vim`)
2. Highlight the `Search` group with something completely different.
    For example, this is how you would make the background _bright green_ when searching: `hi Search guibg=#00FF00`.

**Comment by WirlyWirly** [comment]
Thank you, that put me in the right direction. The gui naming was confusing me, I thought it was something that would only apply to gVim, not from running vim through bash.

For anyone else that may have this question, here's a bit more info I've uncovered that I thought would be useful...

Checkout the help file for a list of group names, their description, as-well as an example of their current color settings.

```
:h highlight-groups
```

You can then use that group name to get some more info about the current highlighting, such as the hex color...
```
:hi {group_name}
```

Over-ride the theme colors by using `guifg` (text color) or `guibg` (background color).

```
:hi {group_name} guifg=#000000
```

You can clear any current colors by using `none`...
```
:hi {group_name} none
```

In the original ayu theme, the `IncSearch` group adapts to the current result, which I was able to get working again with these commands...

```vim
:hi IncSearch none

:hi IncSearch cterm=reverse
```

Adding these tweaks to my vimrc is exactly what I needed. Thanks again for maintaining this great theme @Luxed, I've been using Ayu since week 1 of learning to code, never looked for an alternative because this is THE theme for me 👍
