### ISSUE TITLE
Incorrect Loading with Vim8 Native Pack Management

### ISSUE THREAD

**Issue by willwillsiii** [Luxed/ayu-vim#26]
It seems that this repository is currently incompatible with vim8's native package management. In particular, it seems the `colors` directory is run before `autoload`, and therefore the necessary functions aren't defined yet.

Setting after vim has loaded through manually calling `colorscheme` seems to work fine, but doing so through `~/.vimrc` produces the above issue.

**Comment by Luxed** [comment]
I have a [minpac](https://github.com/k-takata/minpac) (which uses the Vim8 package management feature) based configuration for testing on Vim. I don't have this issue.
`autoload` is lazy. It can be used from anywhere, the files will load on demand _if_ they are in the runtime path.

I've also just tested by manually putting the plugin in `~/.vim/pack/manual/start/ayu-vim` and it works correctly.
If you want to put the colorscheme in `opt` for some reason, you'll need to do `packadd ayu-vim` before using it for sure.

**Comment by willwillsiii** [comment]
I have the plugin added to `~/.vim/pack/colors/start/ayu-vim`. After starting vim, I get the following output:
```
Error detected while processing /home/user/.vim/pack/colors/start/ayu-vim/colors/ayu.vim:
line   18:
E117: Unknown function: ayu#hi
line   19:
E117: Unknown function: ayu#hi
line   20:
E117: Unknown function: ayu#hi
[...]
line  587:
E117: Unknown function: ayu#hi
Press ENTER or type command to continue
```
along with a messed up colorscheme.

I'm not sure what the reason for the difference in loading order is. I realized shortly after posting this issue it could be remedied by explicitly calling `packadd ayu-vim` before `colorscheme ayu` in `~/.vimrc`, but that shouldn't be necessary given the plugin is in `~/.vim/pack/colors/start/`. Not sure why using packadd changes the load order, but it seems it does as I don't get any output this way.

**Comment by Luxed** [comment]
I was able to reproduce with Vim 8.1 and 8.2.
However, it seems to work fine with Vim 9.0.
I think this is a bug. There's nothing I can do I think, you'll have to add `packadd ayu-vim` manually.
Is the theme working properly with this "fix"?

**Comment by willwillsiii** [comment]
Sorry for the delay. It seems to be working with the packadd addition. I'll close the issue.
