### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by jan-bruckner** [Luxed/ayu-vim#28]
Starting with commit d6fc9740e61c186f262aa03c0b31951bc70dfb58, I'm getting the following error when starting Vim:
```
Error detected while processing /home/<user>/.vimrc[133]../home/<user>/.vim/plugged/ayu-vim/colors/ayu.vim:
line  395:
W18: Invalid character in group name
Press ENTER or type command to continue
```

```
%vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 03 2023 07:45:49)
Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919
```

I know the version is ancient, but that's what I'm stuck with at the moment, unfortunately. Maybe you can still make it work again?

**Comment by Luxed** [comment]
I'm so sorry, I keep forgetting that Vim doesn't support the highlight groups that Neovim uses now.
It should have been fixed by the latest commit.

**Comment by jan-bruckner** [comment]
Thanks so much for the really fast fix!
