### ISSUE TITLE
Highlighting of special characters in mappings buffer are difficult to read

### ISSUE THREAD

**Issue by willwillsiii** [Luxed/ayu-vim#29]
When viewing the current mappings in Vim through something like `:nmap`, the resulting text is very hard to read for special characters:
![image](https://user-images.githubusercontent.com/24965267/233203322-101c2fe9-1ff1-4cbd-8124-166f714c17d8.png)

**Comment by Luxed** [comment]
Hmmm, yeah, that's true. I'll look into it when I have some time.
