### ISSUE TITLE
Error color readability

### ISSUE THREAD

**Issue by doubledup** [Luxed/ayu-vim#32]
I've found the ErrorMsg and Error colors hard to read with the light foreground (editor_fg):

### ErrorMsg

<img width="262" alt="errormsg-light-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/52a5c192-3953-461e-87bb-71f50ce1ea69">

<img width="266" alt="errormsg-mirage-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/18bd9f20-1a28-44cd-875a-7db62426ee84">

<img width="264" alt="errormsg-dark-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/3a03d901-bc73-4368-869a-e79a100fc95c">

### Error

<img width="305" alt="error-light-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/751e29c0-7905-4ba2-8621-053ec8f513ea">

<img width="306" alt="error-mirage-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/ec948b83-c1c8-487b-b372-982668ae7ce5">

<img width="304" alt="error-dark-foreground" src="https://github.com/Luxed/ayu-vim/assets/26876072/4f1ad58b-eb68-438f-83ed-6de0986793cc">

Switching to the background color (editor_bg) looks easier to read:

### ErrorMsg

<img width="263" alt="errormsg-light-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/7a33158e-e939-4ef6-9e5d-0884fedb77f9">

<img width="264" alt="errormsg-mirage-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/b1ceb870-19e6-4c1a-af75-e70a7f4f7a81">

<img width="262" alt="errormsg-dark-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/61323f0f-2e04-4c8f-b935-eb28f4e1a1da">

### Error

<img width="306" alt="error-light-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/a138071c-dc6d-47f4-888a-10aecdbb57b3">

<img width="305" alt="error-mirage-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/f0323fb9-a470-4524-87db-895af27469c4">

<img width="307" alt="error-dark-background" src="https://github.com/Luxed/ayu-vim/assets/26876072/48fdab0b-2bea-4271-ab65-65d520a87e25">

Before opening a PR, I want to check some things:

1. Do you think that the error colors should change to something other than editor_fg?
2. If so, should they change to use the editor_bg or a different color? ie. for ErrorMsg and Error, use common_error with editor_bg instead of with editor_fg.
3. ErrorMsg uses common_error as the foreground, but Error uses common_error as the background. Should we change one of them to match the other? If so, which one?

**Comment by doubledup** [comment]
My take:

1. The error colors should switch from editor_fg as that's hard to read with the common_error red.
2. editor_bg is a fine choice, though maybe there's a better one that will distinguish the error from the rest of the interface more clearly.
3. The editor_bg samples for ErrorMsg above look better than the Error samples to me. I'd prefer red text to a red background.

**Comment by doubledup** [comment]
Also thank you so much for maintaining this! Ayu stopped my colorscheme hopping years ago and I've used it everywhere every day since.

**Comment by Luxed** [comment]
I've had the same thought when I started using the theme a long time ago.  
However, I get errors so rarely that it never bothered me enough to take the time to fix it.  

I like your proposition. If I understand correctly, this is what you would do, right?
- `Error`: `common_error` background, `editor_bg` foreground
- `ErrorMsg`: no background, `common_error` foreground

This is what it would look like with Fugitive (`Error`) and a command line error (`ErrorMsg`):
![image](https://github.com/Luxed/ayu-vim/assets/10234894/8bbecb85-fd4a-4422-962d-069708c002e2)

I think we can have them both just be a foreground, like this:
![image](https://github.com/Luxed/ayu-vim/assets/10234894/66ad0b1b-62e6-464a-8fb8-642929b5b059)

The last one looks cleaner. It doesn't "pop out" as much, but I think it's okay. You can go with that!

**Comment by doubledup** [comment]
I meant to suggest `common_error` foreground and `editor_bg` background for both `Error` and `ErrorMsg`, which is the second suggestion. PR opened!
