### ISSUE TITLE
Using ayu in vim 9.1.100

### ISSUE THREAD

**Issue by koritnik** [Luxed/ayu-vim#34]
Activating the colorscheme does not work in my case. It results in a green background. Any ideas, whats going wrong? Thank you.
<img width="1008" alt="Bildschirmfoto 2024-02-22 um 09 46 13" src="https://github.com/Luxed/ayu-vim/assets/1124867/757240e9-ba33-4e68-b3d0-84f07fbc9cd9">

**Comment by Luxed** [comment]
I could not reproduce the issue with Vim 9.1 or Vim 9.0.
What terminal are you using?
Did you make sure your configuration contains `set termguicolors`? Does your terminal support 24bit colors?
Did you make sure you have the proper configuration in the proper order?
Are you sure you are using the right fork of the theme?
Are you using the latest commit?

**Comment by koritnik** [comment]
Okay, wasnt aware that the default terminal on mac doesnt support 24bit colors. in iterm it works. Thanks for your time and patience.
