### ISSUE TITLE
The colors of vim-floaterm are inconsistent

### ISSUE THREAD

**Issue by ptr7F** [Luxed/ayu-vim#35]
Using [vim-floaterm ](https://github.com/voldikss/vim-floaterm)to create a new terminal will look like this:
![image](https://github.com/Luxed/ayu-vim/assets/43652659/88ac6993-f988-472c-91f1-eeb5b299ea12)
The ideal color should look like this:
![image](https://github.com/Luxed/ayu-vim/assets/43652659/b9d7f4bc-4b56-4f46-9a57-82319971a226)

How to adjust colors specifically for [vim-floaterm](https://github.com/voldikss/vim-floaterm)？

update:
I added a rule and it works
```
" vim-floaterm: {{{
call ayu#hi('FloatermBorder', 'editor_fg', '')
" }}}
```

Can you take a look at the [vimspector ](https://github.com/puremourning/vimspector)plugin? The colors of those buttons look a bit inconsistent
![image](https://github.com/Luxed/ayu-vim/assets/43652659/e3a29452-da83-4d2f-9b5f-d4be778d70f7)

**Comment by Luxed** [comment]
Hello there, sorry for the slow response.
I'll look into those two when I have some time.
The floaterm fix you gave seems to be simple enough. But vimspector will require a bit more work.

**Comment by ptr7F** [comment]
Thank you for your response. Take your time; I appreciate your effort and support.

**Comment by Luxed** [comment]
I finally took some time to look into vimspector.
I have 2 solutions, one that's "low" contrast and the other that's "high" contrast.

Low contrast:
![image](https://github.com/Luxed/ayu-vim/assets/10234894/87eb83df-f5c1-4691-8c80-09d3136cebd7)

High contrast:
![image](https://github.com/Luxed/ayu-vim/assets/10234894/c2258f9b-78e1-40f9-998c-bba3553433dd)


Even though the high contrast version makes buttons more readable, it also makes the UI look more busy.
So with that in mind, I'd rather go with the low contrast option.
Do you have any preference?

**Comment by ptr7F** [comment]
I personally prefer the High contrast version because the gray buttons on the Low contrast version look like they can't be clicked.

**Comment by Luxed** [comment]
> I personally prefer the High contrast version because the gray buttons on the Low contrast version **look like they can't be clicked.**

I never thought about it this way. Very interesting.
I already never really thought about "clickable" buttons in Vim since that makes no sense in my head. On top of that, instead of disabling buttons, I would expect buttons to simply not be shown at all.
Anyway, I will take your feedback into consideration and will commit the high contrast version!

**Comment by ptr7F** [comment]
Thanks for the work, it looks good now.
