### ISSUE TITLE
Lua reimplementation

### ISSUE THREAD

**Issue by Shatur** [Luxed/ayu-vim#7]
Hi! Thank you for working on it! I [re-implemented](https://github.com/Shatur95/neovim-ayu) this theme in lua. Could be useful for Neovim-only users.

**Comment by Luxed** [comment]
I am already a Neovim-only user. There are currently no real reason to convert a theme to lua (at least for me).
I am opened to add lua code, but only if it is not _needed_ so Vim users can continue to use this plugin.
I like the way you did the configuration with the "overrides" though.
Anyway, I'll close this issue and add a "related projects" section or something like that to mention your conversion!

**Comment by Shatur** [comment]
Yes, just wanted to let you know :)

I originally wanted to make some opionated changes to the theme in my configuration, but then decided to just rewrite it in lua.
